#!/bin/bash
echo using CC=$CC
echo using CXX=$CXX
set -ex
test -d libfmt || git clone https://github.com/fmtlib/fmt libfmt
cd libfmt
git fetch
git checkout 4.x || git checkout -b 4.x origin/4.x
git merge origin/4.x
cmake .
make fmt
